<?php

namespace Bundles\StoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Bundles\StoreBundle\Entity\Product;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
    public function save($obj)
    {
        $em=$this->getEntityManager();
        $em->persist($obj);
        $em->flush();
    }
    public function create($obj)
    {
       // $obj=new Product();
        $this->save($obj);

    }
}
