<?php

namespace Bundles\StoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ValParamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValParamRepository extends EntityRepository
{
    public function getParam($params)
    {
        //dump($brends);
        $qb = $this->createQueryBuilder('p');
        $qb->select('p.value');
        $qb->where('p.parametrs = :params')
            ->setParameter('params', $params);
        $qb->distinct();
       /* if($brends){
            foreach($brends as $brend){
                $qb->andWhere('p.brend IN (:brends)')
                    ->setParameter('brends', $brends);

            }
        }*/

        /*if($fasilities){
            foreach($fasilities as $fas){
                $qb->andWhere(':fas MEMBER OF p.fasilities')
                   ->setParameter('fas', $fas);
            }
        }*/

        return $qb->getQuery()->getResult();
    }

    public function getObjByValue($array)
    {
        $qb = $this->createQueryBuilder('p');
        foreach($array as $key=>$value)
        {
            $qb->orWhere('p.parametrs= :id')
                ->setParameter('id', $key);
            $qb->andWhere('p.value IN (:val)')
                ->setParameter('val', $value);
        }
        return $qb->getQuery()->getResult();
    }
}
